[project]
name = "app"
version = "1.0.0"
description = "A very simple Flask App for EC2 web server deployment testing"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
